<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="frmBondingRequisition.aspx.cs" Inherits="frmBondingRequisition" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
    <script language="javascript" type="text/javascript" >

        function isNumber(evt) {
            evt = (evt) ? evt : window.event;
            var charCode = (evt.which) ? evt.which : evt.keyCode;
            if (charCode != 46 && charCode > 31
            && (charCode < 48 || charCode > 57)) {
                return false;
            }
            return true;
        }
        function LoadModalDiv() {

            var bcgDiv = document.getElementById("divBackground");
            bcgDiv.style.display = "block";
        }
        function HideModalDiv() {

            var bcgDiv = document.getElementById("divBackground");
            bcgDiv.style.display = "none";
        }
   
</script>
<div></div>
    <div id="frmMainDiv" style="background-color:White; width:100%;">
   
<table style="width:100%;">
<tr>
<td style="width:95%; padding-top:10px; height: 10px;" align="center"> 
    <asp:HiddenField ID="hfMstID" runat="server" Visible="False" />
    </td>
<td style="width:5%; height: 10px;"></td>
</tr>
<tr>
<td style="width:2%; padding-top:10px;" align="center"> 
<table style="width:100%;">
<tr>
<td style="width:15%; " align="left" valign="top" rowspan="4">
<fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;line-height:2.5em;"><legend style="color: maroon;"><b>Select Option</b></legend>
<asp:Panel ID="pnlTreeView" runat="server"  ScrollBars="Auto" Height="200px">
    <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False" Width="100%"
             onselectednodechanged="TreeView1_SelectedNodeChanged" ImageSet="Msdn"
        ForeColor="Blue" ParentNodeStyle-ForeColor="Green" Font-Bold="True">
        <ParentNodeStyle ForeColor="Green" />
        <SelectedNodeStyle Font-Underline="False" HorizontalPadding="3px" 
                VerticalPadding="2px" BackColor="White" BorderColor="#888888" 
                BorderStyle="Solid" BorderWidth="1px" />
        
        <NodeStyle Font-Size="8pt" ForeColor="Black" HorizontalPadding="2px" 
                NodeSpacing="2px" VerticalPadding="3px" Font-Names="Verdana" />
    </asp:TreeView>
</asp:Panel>
</fieldset></td>
<td style="width:1%;">&nbsp;</td>
<td style="width:60%;  vertical-align:top;" align="left">
   <fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;"><legend style="color: maroon;">
     <b>
        Requisition Order </b></legend>
    <table style="width: 100%">
        <tr>
            <td style="width: 15%; font-weight: 700;">
                Code</td>
            <td style="width: 35%">
                <asp:TextBox ID="txtManufactureCode" runat="server" AutoPostBack="False" 
                    Font-Size="8pt"  SkinId="tbPlain" TabIndex="6" 
                    Width="70%" ReadOnly="True"></asp:TextBox>
              
            </td>
            <td style="width: 25%" align="right">
                <strong>Date</strong></td>
                <td style="width: 25%">
                    <asp:TextBox ID="txtManufactureDate" runat="server" AutoPostBack="False" 
                    Font-Size="8pt" placeholder="dd/MM/yyyy" SkinId="tbPlain" TabIndex="6" 
                    Width="70%"></asp:TextBox>
                <ajaxToolkit:CalendarExtender ID="Calendarextender1" runat="server" 
                    Format="dd/MM/yyyy" TargetControlID="txtManufactureDate" /></td>
        </tr>
        <tr>
            <td style="width: 15%; font-weight: 700;">
                    Requisition By</td>
            <td style="width: 35%">
                 <asp:DropDownList ID="ddlManufacturedBy" runat="server" Width="98%">
                 </asp:DropDownList>
            </td>
            <td style="width:25%; font-weight: 700;" align="right">
                Exp. Delivery Date</td>
                <td style="width: 25%">
               
                    <asp:TextBox ID="txtExpDeliveryDate" runat="server" AutoPostBack="False" 
                        Font-Size="8pt" placeholder="dd/MM/yyyy" SkinId="tbPlain" TabIndex="6" 
                        Width="70%"></asp:TextBox>
                    <ajaxToolkit:CalendarExtender ID="Calendarextender2" runat="server" 
                        Format="dd/MM/yyyy" TargetControlID="txtExpDeliveryDate" />
               
            </td>
        </tr>
        <tr>
            <td style="width: 15%; font-weight: 700;">
                    Remarks</td>
            <td colspan="2">
                <asp:TextBox ID="txtremarks" runat="server" AutoPostBack="False" 
                    Font-Size="8pt"  SkinId="tbPlain" 
                    Width="99%"></asp:TextBox>
               
            </td>
                <td style="width: 25%">
                    &nbsp;</td>
        </tr>
    </table>
    
    </fieldset>
     

</td>
</tr>
<tr>
<td style="width:1%;"></td>
<td style="width:60%;  vertical-align:top;" align="left">

    

     
     

    

    
 <asp:Panel ID="pnlReceivedFinal" runat="server">
    <fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;"><legend style="color: maroon;">
     <b>
         <asp:Label ID="lblreceivedFianl" runat="server" Text="Final Received "></asp:Label> </b></legend>
<div>
     <table style="width: 100%">
         <tr>
             <td style="width: 35%">
                 <asp:Label ID="lblItemIDFinal" runat="server" 
                Visible="False"></asp:Label>
             </td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
         </tr>
         <tr>
             <td style="width: 35%; font-weight: 700; height: 18px;">
                 Search Product <span style="color: #FF0000">*</span></td>
             <td style="width: 12%; font-weight: 700; height: 18px;">
                 Length (Meter)&nbsp; <span style="color: #FF0000">*</span></td>
             <td style="width: 12%; height: 18px; font-weight: 700;">
                 Width (Meter)&nbsp; <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; height: 18px; font-weight: 700;">
                 Thikness(MM) <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; height: 18px; font-weight: 700;">
                 Quantity(Roll) <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; height: 18px;">
             </td>
             <td style="width: 10%; height: 18px;">
             </td>
         </tr>
         <tr>
             <td style="width: 35%">
               <%--  <asp:TextBox ID="txtItemReceivedFinal" runat="server" 
                autocomplete="off" AutoPostBack="true" Font-Size="8pt" onFocus="this.select()"  SkinId="tbPlain" 
                Text='<%#Eval("item_desc")%>' Width="95%" 
                     ontextchanged="txtItemReceivedFinal_TextChanged"></asp:TextBox>
                 <ajaxToolkit:AutoCompleteExtender ID="autoComplete3" runat="server" 
                     CompletionInterval="1000" CompletionSetCount="12" 
                EnableCaching="true" MinimumPrefixLength="1" ServiceMethod="GetFGAndCMNItems" 
                ServicePath="AutoComplete.asmx" TargetControlID="txtItemReceivedFinal" />
                --%>
                
                <asp:TextBox ID="txtItemReceivedFinal" runat="server" autocomplete="off" 
                     AutoPostBack="true" Font-Size="8pt" onFocus="this.select()" 
                    SkinId="tbPlain" 
                     Text='<%#Eval("item_desc")%>' Width="95%" 
                     ontextchanged="txtItemReceivedFinal_TextChanged">
                </asp:TextBox>
                 <ajaxToolkit:AutoCompleteExtender ID="autoComplete1" runat="server" 
                     CompletionInterval="1000" CompletionSetCount="12" EnableCaching="true"
                     MinimumPrefixLength="1" ServiceMethod="GetMAnufactureStockSearch" 
                     ServicePath="AutoComplete.asmx" TargetControlID="txtItemReceivedFinal" />

             </td>
             <td style="width: 12%">
                 <asp:DropDownList ID="ddllenthReceivedFinal" runat="server" 
                Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 12%">
                 <asp:DropDownList ID="ddlWidthReceivedFinal" runat="server" 
                Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 10%">
                 <asp:DropDownList ID="ddlThiknessReceivedFinal" runat="server" Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 10%">
                 <asp:TextBox ID="txtquantityReceivedFinal" runat="server" 
                CssClass="tbc" Font-Size="8pt" onFocus="this.select()" 
                onkeypress="return isNumber(event)" SkinId="tbPlain" Width="90%"></asp:TextBox>
             </td>
             <td align="right" style="width: 10%">
                 <asp:Button ID="BtnAddReceivedFinal" runat="server" 
                BorderStyle="Outset" BorderWidth="1px" Height="25px" onclick="BtnAddReceivedFinal_Click" 
                TabIndex="901" Text="Add" ToolTip="Save or Update Record" Width="95%" />
             </td>
             <td align="right" style="width: 10%">
                 <asp:Button ID="BtnClearReceivedFinal" runat="server" 
                BorderStyle="Outset" BorderWidth="1px" Height="25px" TabIndex="901" Text="Clear" 
                ToolTip="Save or Update Record" Width="95%" 
                     onclick="BtnClearReceivedFinal_Click" />
             </td>
         </tr>
         <tr>
             <td style="width: 35%">
                 &nbsp;</td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
         </tr>
         <tr>
             <td colspan="7">
                 <fieldset 
                style="vertical-align: top; border: solid 1px #8BB381;text-align:left;">
                     <legend style="color: maroon; font-weight: 700;">Received Item Details </legend>
                     <asp:GridView ID="dgReceivedFinal" runat="server" 
                    AutoGenerateColumns="False" onrowdeleting="dgReceivedFinal_RowDeleting" 
                         Width="96%" CssClass="recGrid">
                         <Columns>
                             <asp:TemplateField>
                                 <ItemTemplate>
                                     <asp:ImageButton ID="lbDelete1" runat="server" 
                                    CausesValidation="False" CommandName="Delete" ImageAlign="Middle" 
                                    ImageUrl="~/img/delete.png" Text="Delete" />
                                 </ItemTemplate>
                                 <ItemStyle Font-Size="8pt" HorizontalAlign="Center" 
                                Width="4%" />
                             </asp:TemplateField>
                             <asp:BoundField DataField="Name" HeaderText="ItemName" />
                             <asp:BoundField DataField="Length" HeaderText="Length" />
                             <asp:BoundField DataField="Width" HeaderText="Width" />
                             <asp:BoundField DataField="Thikness" 
                            HeaderText="Thikness" />
                             <asp:BoundField DataField="Quantity" 
                            HeaderText="Quantity" />
                         </Columns>
                     </asp:GridView>
                 </fieldset>
             </td>
         </tr>
     </table>
      </div>
    </fieldset>
    </asp:Panel>
   

   

</td>
</tr>
<tr>
<td style="width:1%;">&nbsp;</td>
<td style="width:60%;  vertical-align:top;" align="left">
    &nbsp;</td>
</tr>
<tr>
<td style="width:1%;">&nbsp;</td>
<td style="width:60%;  vertical-align:top;" align="left">
                     <asp:GridView ID="dghistory" runat="server" 
                    AutoGenerateColumns="False" Width="96%" 
                         onrowdeleting="dgConsumption_RowDeleting" 
        CssClass="mGrid" onselectedindexchanged="dghistory_SelectedIndexChanged" 
                         onrowdatabound="dghistory_RowDataBound">
                         <Columns>
                             <asp:CommandField ShowSelectButton="True" />
                             <asp:BoundField DataField="ID" HeaderText="ID" />
                             <asp:BoundField DataField="RequisitionByName" HeaderText="Requisition By" >
                             <ItemStyle Width="30%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="ManufagchuredDate" HeaderText="Date" >
                             <ItemStyle Width="20%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="Remarks" 
                            HeaderText="Remarks" />
                         </Columns>
                     </asp:GridView>
    

     

</td>
</tr>
<tr>
<%--pageFooterWrapper--%>
<td style="height:15px; text-align:center; " colspan="3" align="center">
        <table   id="pageFooterWrapper" >
            <tr>
                <td align="center" style="width:15%; vertical-align:middle;">
        <asp:Button  ID="BtnDeletess" runat="server"  ToolTip="Delete Record"  TabIndex="903" 
            onclientclick="javascript:return window.confirm('are u really want to delete these data')"             
            Text="Delete"
             Width="110px" Height="30px" BorderStyle="Outset" BorderWidth="1px" onclick="BtnDeletess_Click" 
                        /></td>
                <td align="center" style="width:15%; vertical-align:middle;">
        <asp:Button ID="BtnSavess" 
            runat="server" ToolTip="Save or Update Record" TabIndex="901" Text="Save"             
             Width="110px" Height="30px" BorderStyle="Outset" BorderWidth="1px" 
                        onclick="BtnSavess_Click" /></td>
                <td align="center" style="width:15%; vertical-align:middle;">
        <asp:Button ID="BtnReset" runat="server" ToolTip="Clear Form" TabIndex="904"   
            Text="Clear" 
             Width="110px" Height="30px" BorderStyle="Outset" BorderWidth="1px" 
                        onclick="BtnReset_Click1" />
                </td>   
                
                
          <td align="center" style="width:15%; vertical-align:middle;">
        <asp:Button ID="btnPrint" runat="server" ToolTip="Clear Form" TabIndex="904"   
            Text="Print" 
             Width="110px" Height="30px" BorderStyle="Outset" BorderWidth="1px" 
                        onclick="btnPrint_Click" />
                </td>                
            </tr>
        </table>
    </td>
    </tr>
<tr>
<td style="height:15px; " colspan="3">
       <br />
    </td>
  </tr>

</table>
</td>
<td style="width:1%;"></td>
</tr>
<tr>
<td style="width:2%; padding-top:10px;" align="center"> 
    &nbsp;</td>
<td style="width:1%;">&nbsp;</td>
</tr>
</table>
</div>
</asp:Content>
