<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="frmMAnufacturingInformation.aspx.cs" Inherits="frmMAnufacturingInformation" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
    <script language="javascript" type="text/javascript" >

     function isNumber(evt) {
         evt = (evt) ? evt : window.event;
         var charCode = (evt.which) ? evt.which : evt.keyCode;
         if (charCode != 46 && charCode > 31
            && (charCode < 48 || charCode > 57)) {
             return false;
         }
         return true;
     }
     function LoadModalDiv() {

         var bcgDiv = document.getElementById("divBackground");
         bcgDiv.style.display = "block";
     }
     function HideModalDiv() {

         var bcgDiv = document.getElementById("divBackground");
         bcgDiv.style.display = "none";
     }
   
</script>
<div></div>
    <div id="frmMainDiv" style="background-color:White; width:100%;">
   
<table style="width:100%;">
<tr>
<td style="width:95%; padding-top:10px; height: 10px;" align="center"> 
    <asp:HiddenField ID="hfMstID" runat="server" Visible="False" />
    </td>
<td style="width:5%; height: 10px;"></td>
</tr>
<tr>
<td style="width:2%; padding-top:10px;" align="center"> 
<table style="width:100%;">
<tr>
<td style="width:15%; " align="left" valign="top" rowspan="4">
<fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;line-height:2.5em;"><legend style="color: maroon;"><b>Select Option</b></legend>
<asp:Panel ID="pnlTreeView" runat="server"  ScrollBars="Auto" Height="200px">
    <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False" Width="100%"
             onselectednodechanged="TreeView1_SelectedNodeChanged" ImageSet="Msdn"
        ForeColor="Blue" ParentNodeStyle-ForeColor="Green" Font-Bold="True">
        <ParentNodeStyle ForeColor="Green" />
        <SelectedNodeStyle Font-Underline="False" HorizontalPadding="3px" 
                VerticalPadding="2px" BackColor="White" BorderColor="#888888" 
                BorderStyle="Solid" BorderWidth="1px" />
        
        <NodeStyle Font-Size="8pt" ForeColor="Black" HorizontalPadding="2px" 
                NodeSpacing="2px" VerticalPadding="3px" Font-Names="Verdana" />
    </asp:TreeView>
</asp:Panel>
</fieldset></td>
<td style="width:1%;">&nbsp;</td>
<td style="width:60%;  vertical-align:top;" align="left">
   <fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;"><legend style="color: maroon;">
     <b>
         Manufacture Information </b></legend>
    <table style="width: 100%">
        <tr>
            <td style="width: 15%; font-weight: 700;">
                Production Code</td>
            <td style="width: 35%">
                <asp:TextBox ID="txtManufactureCode" runat="server" AutoPostBack="False" 
                    Font-Size="8pt"  SkinId="tbPlain" TabIndex="6" 
                    Width="70%" ReadOnly="True"></asp:TextBox>
              
            </td>
            <td style="width: 25%">
                &nbsp;</td>
                <td style="width: 25%">
                    &nbsp;</td>
        </tr>
        <tr>
            <td style="width: 15%; font-weight: 700;">
                    Prepared By</td>
            <td style="width: 35%">
                 <asp:DropDownList ID="ddlManufacturedBy" runat="server" Width="98%">
                 </asp:DropDownList>
            </td>
            <td style="width:25%; font-weight: 700;" align="right">
                Manufacture Date</td>
                <td style="width: 25%">
                <asp:TextBox ID="txtManufactureDate" runat="server" AutoPostBack="False" 
                    Font-Size="8pt" placeholder="dd/MM/yyyy" SkinId="tbPlain" TabIndex="6" 
                    Width="70%"></asp:TextBox>
                <ajaxToolkit:CalendarExtender ID="Calendarextender1" runat="server" 
                    Format="dd/MM/yyyy" TargetControlID="txtManufactureDate" />
            </td>
        </tr>
        <tr>
            <td style="width: 15%; font-weight: 700;">
                    Remarks</td>
            <td colspan="2">
                <asp:TextBox ID="txtremarks" runat="server" AutoPostBack="False" 
                    Font-Size="8pt"  SkinId="tbPlain" 
                    Width="99%"></asp:TextBox>
               
            </td>
                <td style="width: 25%">
                    &nbsp;</td>
        </tr>
    </table>
    
    </fieldset>
     

</td>
</tr>
<tr>
<td style="width:1%;"></td>
<td style="width:60%;  vertical-align:top;" align="left">
 &nbsp;<asp:Panel ID="pnlConsumption" runat="server">
     <fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;"><legend style="color: maroon;">
     <b>
         <asp:Label ID="lblConsumption" runat="server" Text="Raw Metarials"></asp:Label> </b></legend>
<div>
     <table style="width: 100%">
         <tr>
             <td style="width: 35%">
                 <asp:Label ID="lblItemIDConsumption" runat="server" 
                Visible="False"></asp:Label>
                  <asp:Label ID="lblManufacturing_StockId" runat="server" 
                Visible="False"></asp:Label>
             </td>
             <td style="width: 12%">
                 <asp:Label ID="LblLength" runat="server" Text="Length *"></asp:Label>
             </td>
             <td style="width: 12%">
                 <asp:DropDownList ID="ddllenthConsumption" runat="server" Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
         </tr>
         <tr>
             <td style="width: 35%; font-weight: 700; height: 18px;">
                 Search Product <span style="color: #FF0000">*</span></td>
             <td style="width: 12%; font-weight: 700; height: 18px;">
                 
                 <%--Length&nbsp; <span style="color: #FF0000">*</span>--%>
                 UOM</td>
             <td style="width: 12%; height: 18px; font-weight: 700;">
               <%--  Width&nbsp; <span style="color: #FF0000">*</span>--%>
                  <asp:Label ID="LblWidth" runat="server" Text="Width *"></asp:Label>
                 </td>
             <td style="width: 10%; height: 18px; font-weight: 700;">
                 <%--Thikness <span style="color: #FF0000">*</span>--%>
                 <asp:Label ID="lblThikness" runat="server" Text="Thikness *"></asp:Label>
                 </td>
             <td style="width: 10%; height: 18px; font-weight: 700;">
                 Quantity <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; height: 18px;">
             </td>
             <td style="width: 10%; height: 18px;">
             </td>
         </tr>
         <tr>
             <td style="width: 35%">
                 <asp:TextBox ID="txtItemConsumption" runat="server" 
                autocomplete="off" AutoPostBack="true" Font-Size="8pt" onFocus="this.select()" 
                SkinId="tbPlain" Text='<%#Eval("item_desc")%>' Width="95%" 
                     ontextchanged="txtItemConsumption_TextChanged"></asp:TextBox>
                 <ajaxToolkit:AutoCompleteExtender ID="autoComplete2" runat="server" 
                     CompletionInterval="1000" CompletionSetCount="12" 
                EnableCaching="true" MinimumPrefixLength="1" 
               
                ServiceMethod="GetItemListExtruderBarcode"  
                ServicePath="AutoComplete.asmx" TargetControlID="txtItemConsumption" />
             </td>
             <td style="width: 12%">
                 <asp:DropDownList ID="ddlUmo" runat="server" Enabled="False" Height="26px" 
                     Width="100%">
                 </asp:DropDownList>
             </td>
             <td style="width: 12%">
                 <asp:DropDownList ID="ddlWidthConsumption" runat="server" 
                Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 10%">
                 <asp:DropDownList ID="ddlThiknessConsumption" runat="server" Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 10%">
                 <asp:TextBox ID="txtquantityConsumption" runat="server" 
                CssClass="tbc" Font-Size="8pt" onFocus="this.select()" 
                onkeypress="return isNumber(event)" SkinId="tbPlain" Width="90%"></asp:TextBox>
             </td>
             <td align="right" style="width: 10%">
                 <asp:Button ID="BtnAddConsumption" runat="server" 
                BorderStyle="Outset" BorderWidth="1px" Height="25px" onclick="BtnAddConsumption_Click" 
                TabIndex="901" Text="Add" ToolTip="Save or Update Record" Width="95%" />

             </td>
             <td align="right" style="width: 10%">
                 <asp:Button ID="BtnClearConsumption" runat="server" 
                BorderStyle="Outset" BorderWidth="1px" Height="25px" TabIndex="901" Text="Clear" 
                ToolTip="Save or Update Record" Width="95%" 
                     onclick="BtnClearConsumption_Click" />
             </td>
         </tr>
         <tr>
             <td style="width: 35%">
                 &nbsp;</td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
         </tr>
         <tr>
             <td colspan="7">
                 <fieldset 
                style="vertical-align: top; border: solid 1px #8BB381;text-align:left;">
                     <legend style="color: maroon; font-weight: 700;">Raw Metrials Item Details </legend>
                     <asp:GridView ID="dgConsumption" runat="server" 
                    AutoGenerateColumns="False" Width="96%" 
                         onrowdeleting="dgConsumption_RowDeleting" CssClass="conGrid">
                         <Columns>
                             <asp:TemplateField>
                                 <ItemTemplate>
                                     <asp:ImageButton ID="lbDelete0" runat="server" 
                                    CausesValidation="False" CommandName="Delete" ImageAlign="Middle" 
                                    ImageUrl="~/img/delete.png" Text="Delete" />
                                 </ItemTemplate>
                                 <ItemStyle Font-Size="8pt" HorizontalAlign="Center" 
                                Width="4%" />
                             </asp:TemplateField>
                             <asp:BoundField DataField="Name" HeaderText="ItemName" >
                             <ItemStyle Width="45%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="Length" HeaderText="Length" />
                             <asp:BoundField DataField="Width" HeaderText="Width" />
                             <asp:BoundField DataField="Thikness" 
                            HeaderText="Thikness" />
                             <asp:BoundField DataField="Quantity" 
                            HeaderText="Quantity" />
                         </Columns>
                     </asp:GridView>
                 </fieldset>
             </td>
         </tr>
     </table>
     </div></fieldset>
    </asp:Panel>
    

     

    <asp:Panel ID="pnlreceived" runat="server">
    <fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;"><legend style="color: maroon;">
     <b>
         <asp:Label ID="lblrecivedPnl" runat="server" Text="Raw Metrials"></asp:Label> </b></legend>
<div>
     <table style="width: 100%">
         <tr>
             <td style="width: 35%">
                 <asp:Label ID="lblItemID" runat="server" Visible="False"></asp:Label>
                 <asp:Label ID="lblItemProductionCode" runat="server" Visible="False"></asp:Label>
             </td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
         </tr>
         <tr>
             <td style="width: 35%">
                   <asp:TextBox ID="txtRequisitionNo" runat="server" AutoPostBack="True" CssClass="tbc" 
            Font-Size="8pt"
            placeholder="Search RO. No" SkinId="tbPlain" TabIndex="3" 
            Width="60%" ontextchanged="txtRequisitionNo_TextChanged"></asp:TextBox>
        <ajaxToolkit:AutoCompleteExtender ID="txtRequisitionNo_AutoCompleteExtender" 
            runat="server" CompletionInterval="20" CompletionSetCount="30" 
            EnableCaching="true" MinimumPrefixLength="2" ServiceMethod="GetRequisitionWithBondingCutting" 
            ServicePath="~/AutoComplete.asmx" TargetControlID="txtRequisitionNo">
        </ajaxToolkit:AutoCompleteExtender>
        <asp:Label ID="lblrequisitionNo" runat="server" Visible="False"></asp:Label>
        </td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
         </tr>
         <%--<tr>
             <td style="width: 35%; font-weight: 700; height: 18px;">
                 Search Product <span style="color: #FF0000">*</span></td>
             <td style="width: 12%; font-weight: 700; height: 18px;">
                 Length&nbsp;(Inch.) <span style="color: #FF0000">*</span></td>
             <td style="width: 12%; height: 18px; font-weight: 700;">
                 Width (Inch)&nbsp; <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; height: 18px; font-weight: 700;">
                 Thikness(mili) <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; height: 18px; font-weight: 700;">
                 Quantity(Roll) <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; height: 18px;">
             </td>
             <td style="width: 10%; height: 18px;">
             </td>
         </tr>--%>
         <tr>
             <td style=" width: 35%">
                 <asp:TextBox ID="txtItemReceived" runat="server" autocomplete="off" 
                     AutoPostBack="true" Font-Size="8pt" onFocus="this.select()" 
                    SkinId="tbPlain" 
                     Text='<%#Eval("item_desc")%>' Width="95%" 
                     ontextchanged="txtItemReceived_TextChanged">
                </asp:TextBox>
                 <ajaxToolkit:AutoCompleteExtender ID="autoComplete1" runat="server" 
                     CompletionInterval="1000" CompletionSetCount="12" EnableCaching="true" 
                     MinimumPrefixLength="1" ServiceMethod="GetMAnufactureStock" 
                     ServicePath="AutoComplete.asmx" TargetControlID="txtItemReceived" />
             </td>
             <td style="width: 12%">
                 <asp:DropDownList ID="ddllenthReceived" runat="server" Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 12%">
                 <asp:DropDownList ID="ddlWidthReceived" runat="server" Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 10%">
                 <asp:DropDownList ID="ddlThiknessReceived" runat="server" Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 10%">
                 <asp:TextBox ID="txtquantityReceived" runat="server" CssClass="tbc" 
                     Font-Size="8pt" onFocus="this.select()" onkeypress="return isNumber(event)" 
                      SkinId="tbPlain"  Width="90%">
                </asp:TextBox>
             </td>
             <td style="width: 10%" align="right">
                 <asp:Button ID="BtnAddReceived" runat="server" BorderStyle="Outset" 
                     BorderWidth="1px" Height="25px" onclick="btnAdd_Click" TabIndex="901" 
                     Text="Add" ToolTip="Save or Update Record" Width="95%" Enabled="False" />
             </td>
             <td style="width: 10%" align="right">
                 <asp:Button ID="BtnClearReceived" runat="server" BorderStyle="Outset" 
                     BorderWidth="1px" Height="25px" onclick="BtnClearReceived_Click" TabIndex="901" 
                     Text="Clear" ToolTip="Save or Update Record" Width="95%" Enabled="False" />
             </td>
         </tr>
         <tr>
             <td style="width: 35%">
                 &nbsp;</td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 12%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
         </tr>
         <tr>
             <td colspan="7">
                
    <fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;">
        <legend style="color: maroon; font-weight: 700;">Item Details Details
     </legend>
     
     
        <asp:GridView ID="dgReceived" runat="server" AutoGenerateColumns="False" 
            Width="96%" onrowdeleting="dgReceived_RowDeleting" CssClass="recGrid">
            <Columns>
             <asp:TemplateField>
                <ItemTemplate>
                <asp:ImageButton ID="lbDelete" runat="server" CausesValidation="False" CommandName="Delete" ImageAlign="Middle" ImageUrl="~/img/delete.png" Text="Delete" />
                </ItemTemplate>
                <ItemStyle Font-Size="8pt" HorizontalAlign="Center" Width="4%" />
            </asp:TemplateField>
                <asp:BoundField DataField="Name" HeaderText="ItemName" />
                <asp:BoundField DataField="Length" HeaderText="Length" />
                <asp:BoundField DataField="Width" HeaderText="Width" />
                <asp:BoundField DataField="Thikness" HeaderText="Thikness" />
                <asp:BoundField DataField="Quantity" HeaderText="Quantity" />
            </Columns>
        </asp:GridView>
     
     
     </fieldset>
     </td>
         </tr>
     </table>
     </div>
    </fieldset>
    </asp:Panel>
    

    
 <asp:Panel ID="pnlReceivedFinal" runat="server">
    <fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;"><legend style="color: maroon;">
     <b>
         <asp:Label ID="lblreceivedFianl" runat="server" Text="Final Received "></asp:Label> </b></legend>
<div>
     <table style="width: 100%">
         <tr>
             <td style="width: 31%">
                 <asp:Label ID="lblItemIDFinal" runat="server" 
                Visible="False"></asp:Label>
             </td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
                 <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 9%">
                 &nbsp;</td>
             <td style="width: 9%">
                 &nbsp;</td>
         </tr>
         <tr>
             <td style="width: 31%; font-weight: 700; height: 18px;">
                 Search Product <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; font-weight: 700; height: 18px;" class="style1">
                 Length (Meter)&nbsp; <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; height: 18px; font-weight: 700;" class="style1">
                 Width (Meter)&nbsp; <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; height: 18px; font-weight: 700;" class="style1">
                 Thikness<br /> (MM) <span style="color: #FF0000">*</span></td>
             <td style="width: 10%; height: 18px; font-weight: 700;" class="style1">
                 Quantity<br /> (Roll) <span style="color: #FF0000">*</span></td>
                 <td style="width: 10%; font-weight: 700;" class="style1">
                     Weight<br /> (KG) <span style="color: #FF0000">*</span></td>
             <td style="width: 9%; height: 18px;">
             </td>
             <td style="width: 9%; height: 18px;">
             </td>
         </tr>
         <tr>
             <td style="width: 31%">
                 <asp:TextBox ID="txtItemReceivedFinal" runat="server" 
                autocomplete="off" AutoPostBack="true" Font-Size="8pt" onFocus="this.select()"  SkinId="tbPlain" 
                Text='<%#Eval("item_desc")%>' Width="95%" 
                     ontextchanged="txtItemReceivedFinal_TextChanged"></asp:TextBox>
                 <ajaxToolkit:AutoCompleteExtender ID="autoComplete3" runat="server" 
                     CompletionInterval="1000" CompletionSetCount="12" 
                EnableCaching="true" MinimumPrefixLength="1" ServiceMethod="GetFGAndCMNItems" 
                ServicePath="AutoComplete.asmx" TargetControlID="txtItemReceivedFinal" />
             </td>
             <td style="width: 10%">
                 <asp:DropDownList ID="ddllenthReceivedFinal" runat="server" 
                Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 10%">
                 <asp:DropDownList ID="ddlWidthReceivedFinal" runat="server" 
                Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 10%">
                 <asp:DropDownList ID="ddlThiknessReceivedFinal" runat="server" Width="96%">
                 </asp:DropDownList>
             </td>
             <td style="width: 10%">
                 <asp:TextBox ID="txtquantityReceivedFinal" runat="server" 
                CssClass="tbc" Font-Size="8pt" onFocus="this.select()" 
                onkeypress="return isNumber(event)" SkinId="tbPlain" Width="90%"></asp:TextBox>
             </td>
             <td style="width: 10%">
                <asp:TextBox ID="txtWeight" runat="server" 
                CssClass="tbc" Font-Size="8pt" onFocus="this.select()" 
                onkeypress="return isNumber(event)" SkinId="tbPlain" Width="90%"></asp:TextBox>
                </td>
             <td align="right" style="width: 9%">
                 <asp:Button ID="BtnAddReceivedFinal" runat="server" 
                BorderStyle="Outset" BorderWidth="1px" Height="25px" onclick="BtnAddReceivedFinal_Click" 
                TabIndex="901" Text="Add" ToolTip="Save or Update Record" Width="95%" />
             </td>
             <td align="right" style="width: 9%">
                 <asp:Button ID="BtnClearReceivedFinal" runat="server" 
                BorderStyle="Outset" BorderWidth="1px" Height="25px" TabIndex="901" Text="Clear" 
                ToolTip="Save or Update Record" Width="95%" 
                     onclick="BtnClearReceivedFinal_Click" />
             </td>
         </tr>
         <tr>
             <td style="width: 31%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 10%">
                 &nbsp;</td>
                 <td style="width: 10%">
                 &nbsp;</td>
             <td style="width: 9%">
                 &nbsp;</td>
             <td style="width: 9%">
                 &nbsp;</td>
         </tr>
       
         <tr>
             <td colspan="8">
                 <fieldset 
                style="vertical-align: top; border: solid 1px #8BB381;text-align:left;">
                     <legend style="color: maroon; font-weight: 700;">Received Item Details </legend>
                     <asp:GridView ID="dgReceivedFinal" runat="server" 
                    AutoGenerateColumns="False" onrowdeleting="dgReceivedFinal_RowDeleting" 
                         Width="96%" CssClass="recGrid">
                         <Columns>
                             <asp:TemplateField>
                                 <ItemTemplate>
                                     <asp:ImageButton ID="lbDelete1" runat="server" 
                                    CausesValidation="False" CommandName="Delete" ImageAlign="Middle" 
                                    ImageUrl="~/img/delete.png" Text="Delete" />
                                 </ItemTemplate>
                                 <ItemStyle Font-Size="8pt" HorizontalAlign="Center" 
                                Width="4%" />
                             </asp:TemplateField>
                             <asp:BoundField DataField="Name" HeaderText="ItemName" />
                             <asp:BoundField DataField="Length" HeaderText="Length" />
                             <asp:BoundField DataField="Width" HeaderText="Width" />
                             <asp:BoundField DataField="Thikness" HeaderText="Thikness" />
                             <asp:BoundField DataField="Quantity" HeaderText="Quantity" />
                             <asp:BoundField DataField="Weight" HeaderText="Weight" />
                         </Columns>
                     </asp:GridView>
                 </fieldset>
                </td>
         </tr>
       
     </table>
      </div>
    </fieldset>
    </asp:Panel>
   

   

</td>
</tr>
<tr>
<td style="width:1%;">&nbsp;</td>
<td style="width:60%;  vertical-align:top;" align="left">
    &nbsp;</td>
</tr>
<tr>
<td style="width:1%;">&nbsp;</td>
<td style="width:60%;  vertical-align:top;" align="left">
                     <asp:GridView ID="dghistory" runat="server" 
                    AutoGenerateColumns="False" Width="96%" 
                         onrowdeleting="dgConsumption_RowDeleting" 
        CssClass="mGrid" onselectedindexchanged="dghistory_SelectedIndexChanged" 
                         onrowdatabound="dghistory_RowDataBound">
                         <Columns>
                             <asp:CommandField ShowSelectButton="True" />
                             <asp:BoundField DataField="ID" HeaderText="ID" />
                             <asp:BoundField DataField="GenerateCode" HeaderText="Production Code" >
                             <ItemStyle Width="20%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="ManufagchuredName" HeaderText="Manufactured By" >
                             <ItemStyle Width="30%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="ManufagchuredDate" HeaderText="Manufactured Date" >
                             <ItemStyle Width="20%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="ProductionCode" 
                            HeaderText="Serial Code" />
                             <asp:BoundField DataField="ProductionParentCode" 
                            HeaderText="Parent Code" />
                         </Columns>
                     </asp:GridView>
    

     

</td>
</tr>
<tr>
<%--pageFooterWrapper--%>
<td style="height:15px; text-align:center; " colspan="3" align="center">
        <table   id="pageFooterWrapper" >
            <tr>
                <td align="center" style="width:15%; vertical-align:middle;">
        <asp:Button  ID="BtnDeletess" runat="server"  ToolTip="Delete Record"  TabIndex="903" 
            onclientclick="javascript:return window.confirm('are u really want to delete these data')"             
            Text="Delete"
             Width="110px" Height="30px" BorderStyle="Outset" BorderWidth="1px" 
                        onclick="BtnDeletess_Click"  /></td>
                <td align="center" style="width:15%; vertical-align:middle;">
        <asp:Button ID="BtnSavess" 
            runat="server" ToolTip="Save or Update Record" TabIndex="901" Text="Save"             
             Width="110px" Height="30px" BorderStyle="Outset" BorderWidth="1px" 
                        onclick="BtnSavess_Click" /></td>
                <td align="center" style="width:15%; vertical-align:middle;">
        <asp:Button ID="BtnReset" runat="server" ToolTip="Clear Form" TabIndex="904"   
            Text="Clear" 
             Width="110px" Height="30px" BorderStyle="Outset" BorderWidth="1px" 
                        onclick="BtnReset_Click1" />
                </td>  
                
                
                 <td align="center" style="width:15%; vertical-align:middle;">
        <asp:Button ID="btnPrint" runat="server" ToolTip="Print PO" Text="Print" 
        Height="30px" Width="110px" BorderStyle="Outset" onclick="btnPrint_Click"  />
                </td>  

                 
                            
            </tr>
        </table>
    </td>
    </tr>
<tr>
<td style="height:15px; " colspan="3">
       <br />
    </td>
  </tr>

</table>
</td>
<td style="width:1%;"></td>
</tr>
<tr>
<td style="width:2%; padding-top:10px;" align="center"> 
    &nbsp;</td>
<td style="width:1%;">&nbsp;</td>
</tr>
</table>
</div>
</asp:Content>

