<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="frmmanufacturedStockInfo.aspx.cs" Inherits="frmmanufacturedStockInfo" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
<script language="javascript" type="text/javascript" >

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode != 46 && charCode > 31
            && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }



    function LoadModalDiv() {

        var bcgDiv = document.getElementById("divBackground");
        bcgDiv.style.display = "block";

    }
    function HideModalDiv() {

        var bcgDiv = document.getElementById("divBackground");
        bcgDiv.style.display = "none";

    }
   
</script>
<div></div>
    <div id="frmMainDiv" style="background-color:White; width:100%;">
   
<table style="width:100%;">
<tr>
<td style="width:95%; padding-top:10px; height: 10px;" align="center"> 
    <asp:HiddenField ID="hfMstID" runat="server" Visible="False" />
    </td>
<td style="width:5%; height: 10px;"></td>
</tr>
<tr>
<td style="width:2%; padding-top:10px;" align="center"> 
<table style="width:100%;">
<tr>
<td style="width:15%; " align="left" valign="top">
<fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;line-height:2.5em;"><legend style="color: maroon;"><b>Select Option</b></legend>
<asp:Panel ID="pnlTreeView" runat="server"  ScrollBars="Auto" Height="200px">
    <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False" Width="100%"
             onselectednodechanged="TreeView1_SelectedNodeChanged" ImageSet="Msdn"
        ForeColor="Blue" ParentNodeStyle-ForeColor="Green" Font-Bold="True">
        <ParentNodeStyle ForeColor="Green" />
        <SelectedNodeStyle Font-Underline="False" HorizontalPadding="3px" 
                VerticalPadding="2px" BackColor="White" BorderColor="#888888" 
                BorderStyle="Solid" BorderWidth="1px" />
        
        <NodeStyle Font-Size="8pt" ForeColor="Black" HorizontalPadding="2px" 
                NodeSpacing="2px" VerticalPadding="3px" Font-Names="Verdana" />
    </asp:TreeView>
</asp:Panel>
</fieldset></td>
<td style="width:1%;">&nbsp;</td>
<td style="width:60%;  vertical-align:top;" align="left">
                     <asp:GridView ID="dghistory" runat="server" 
                    AutoGenerateColumns="False" Width="96%" 
        CssClass="mGrid">
                         <Columns>
                       <%--      <asp:BoundField DataField="name" HeaderText="Item Name" >
                             <ItemStyle Width="15%" />
                             <ItemStyle Width="40%" />
                             </asp:BoundField>--%>
                             <asp:BoundField DataField="ItemsName" HeaderText="Item Name" >
                             <ItemStyle Width="15%" />
                             <ItemStyle Width="40%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="Code" HeaderText="Code" >
                             <ItemStyle Width="15%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="ProductionCode" HeaderText="Production Code" >
                             </asp:BoundField>
                             <asp:BoundField DataField="length" 
                            HeaderText="length" >
                             <ItemStyle Width="15%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="width" 
                            HeaderText="width" >
                             <ItemStyle Width="15%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="thikness" HeaderText="thikness" >
                             <ItemStyle Width="15%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="ClosingStock" HeaderText="Closing Stock">
                             <ItemStyle Width="15%" />
                             </asp:BoundField>
                             <asp:BoundField DataField="CFTClosingStock" HeaderText="CFT ClosingStock">
                             <HeaderStyle HorizontalAlign="Center" />
                             <ItemStyle HorizontalAlign="Right" />
                             </asp:BoundField>
                             
                               <asp:BoundField DataField="SFTClosingStock" HeaderText="SFT ClosingStock">
                             <HeaderStyle HorizontalAlign="Center" />
                             <ItemStyle HorizontalAlign="Right" />
                             </asp:BoundField>
                             
                               <asp:BoundField DataField="SQMClosingStock" HeaderText="SQM ClosingStock">
                             <HeaderStyle HorizontalAlign="Center" />
                             <ItemStyle HorizontalAlign="Right" />
                             </asp:BoundField>
                         </Columns>
                     </asp:GridView>
    

     

</td>
</tr>
<tr>
<%--pageFooterWrapper--%>
<td style="height:15px; text-align:center; " colspan="3" align="center">
        
    </td>
    </tr>
<tr>
<td style="height:15px; " colspan="3">
       <br />
    </td>
  </tr>

</table>
</td>
<td style="width:1%;"></td>
</tr>
<tr>
<td style="width:2%; padding-top:10px;" align="center"> 
    &nbsp;</td>
<td style="width:1%;">&nbsp;</td>
</tr>
</table>
</div>
</asp:Content>

